
export const QASWA_PRODUCTS = [
  'Amsenide 1000ml',
  'Amsenide 100ml',
  'Ben Rold 10% 1000ml',
  'Ben Rold 10% 100ml',
  'Bovigest Powder 100gm',
  'CALCONIL LIQUID 120ml',
  'D- OX Liquid 1000ml',
  'D- OX Liquid 100ml',
  'DMG-DCP Powder 1kg',
  'DMG-DCP Powder 20 kg',
  'DMG-DCP Powder 25kg',
  'DMG-DCP Powder 5KG',
  'Fagoban Powder 12 gm',
  'Gent-Tyrold 150 100ml',
  'Gent-Tyrold 150 50ml',
  'Glymet 25 KG 25kg',
  'HANS-FAXS 100ml',
  'HANS-FAXS 500ml',
  'Harry Mine 100ml',
  'Harry Mine 10ml',
  'Harry Mine 50ml',
  'Harry Sulon 100ml',
  'Harry Sulon 10ml',
  'Harry Sulon 50ml',
  'Harryzen DS 1000ml',
  'Harryzen DS 100ml',
  'Hi Care OS 1000ml',
  'Hi Care OS 120ml',
  'Hi Vit-C Oral Powder 100gm',
  'Hivit-C Oral Powder 100gm',
  'Hoof Guard 29KG 29 KG',
  'Hoof Guard 5KG',
  'Iodo Dip 5KG',
  'Iodo Film 25kg',
  'Iodo Film 25Kg 25kg',
  'Iodo Film 5KG',
  'LABAN POWDER (Jar) 1kg',
  'LABAN POWDER (Pouch) 1kg',
  'LABAN POWDER (Pouch) 20kg DUP',
  'LABAN POWDER (Pouch) 5KG',
  'LABAN POWDER 1kg',
  'LABAN POWDER 20kg DUP',
  'LABAN POWDER 5KG',
  'Lacto Film 25kg',
  'Lacto Film 25Kg 25kg',
  'Lacto Film 5KG',
  'Lewisto 190 100ml',
  'Lewisto 190 50ml',
  'Macrold 1% 100ml',
  'Macrold 1% 10ml',
  'Macrold 1% 50ml',
  'Macrold 2% 100ml',
  'Macrold 2% 10ml',
  'Macrold 2% 50ml',
  'Mineric Forte Powder 1kg',
  'Mineric Forte Powder 20kg DUP',
  'Mineric Forte Powder 5KG',
  'Mox Rold LA 15% 100ml',
  'Mox Rold LA 15% 50ml',
  'PETIMMUN LIQUID 100ml',
  'Ruminex 1kg',
  'Ruminex 20 kg',
  'Ruminex 5KG',
  'TOXIFREE 25kg',
  'TRI Phate 1000ml',
  'TRI Phate 100ml',
  'TRI Phate 500ml',
  'Tronox-340 100ml',
  'Vetcal-D 1000ml',
  'Vetcal-D 500ml',
  'Vetfon 98% 10gm',
  'Colital 1kg'
];

export const AGILE_PRODUCTS = [
  'Black Extreme 5 Ltr',
  'D-Calphos OS',
  'DMG E-SEL 1Ltr',
  'FRA AC34 1 ltr',
  'FRA AC34 10 ltr',
  'FRA AC34 25 ltr',
  'FRA C12 1 Ltr',
  'FRA C12 10 ltr',
  'FRA C12 25 ltr',
  'NCO Skill 200 1Kg',
  'Pulmline D Oral 1 Ltr',
  'Respizan OS 5 Ltr',
  'Vitarich D OP',
  'Norflox P Forte Oral Solution',
  'Colital-50 Oral Powder',
  'Coxidin Oral Powder',
  'Tylconor Oral Solution 1 Ltr',
  'Fosfo Forte Powder',
  'Gumbo Fix Powder 1 Kg',
  'HTM-Ultra Oral Powder',
  'Neoxytal Forte Oral Powder',
  'Coxidin',
  'Tylovalo Forte Granules',
  'Neotal 72% Oral Powder'
];

export const DEFAULT_PRODUCTS = ['Gambo Fix', 'Tylovalo Forte', 'Farasi 12', 'Fara AC 34', 'Toxy Free'];
