import { Lead, TimelineEntry } from './types';

export const leads: Lead[] = [
  {
    id: '1',
    businessName: 'Al Noor Poultry Farm',
    contactPerson: 'Mr. Imran Khalid',
    segment: 'Broiler',
    phone: '0300-1234567',
    city: 'LAHORE',
    brick: 'CANTT',
    group: 'AGILE',
    product: 'FRA AC34 1 ltr',
    manager: 'Adil BSM',
    province: 'Punjab',
    date: '2026-05-10',
    status: 'Confirm Order',
    potential: '60,000',
    visitNotes: 5,
    lineManagerNotes: 7,
    managerNotes: 4,
    confirmOrder: 5,
    totalSale: 'PKR 450,000',
    recovery: 'PKR 320,000',
  },
  {
    id: '2',
    businessName: 'Green Valley Dairy Farm',
    contactPerson: 'Mr. Usman Tariq',
    segment: 'Farmer',
    phone: '0300-9876543',
    city: 'KASUR',
    brick: 'Pattoki',
    group: 'QASWA',
    product: 'Tylovalo Forte Granules',
    manager: 'Naveed',
    province: 'Punjab',
    date: '2026-05-12',
    status: 'Recovery',
    potential: '100',
    visitNotes: 4,
    lineManagerNotes: 6,
    managerNotes: 3,
    confirmOrder: 6,
    totalSale: 'PKR 600,000',
    recovery: 'PKR 510,000',
  },
  {
    id: '3',
    businessName: 'VetCare Clinic',
    contactPerson: 'Dr. Sam Mehmood',
    segment: 'VO',
    phone: '0321-4567890',
    city: 'Karachi',
    brick: 'SADDAR',
    group: 'QASWA',
    product: 'Black Extreme 5 Ltr',
    manager: 'Anwer',
    province: 'Sindh',
    date: '2026-05-13',
    status: 'Recovery',
    potential: '6-8 / day',
    visitNotes: 3,
    lineManagerNotes: 5,
    managerNotes: 2,
    confirmOrder: 2,
    totalSale: 'PKR 85,000',
    recovery: 'PKR 60,000',
  },
  {
    id: '4',
    businessName: 'Punjab Breeder Complex',
    contactPerson: 'Mr. Naveed Akhtar',
    segment: 'Breeder',
    phone: '0345-1234567',
    city: 'SAHIWAL',
    brick: 'Chichawatni',
    group: 'AGILE',
    product: 'Fara AC 34',
    manager: 'Dr. Bilal',
    province: 'Punjab',
    date: '2026-05-14',
    status: 'Confirm Order',
    potential: '50,000 bags',
    visitNotes: 6,
    lineManagerNotes: 8,
    managerNotes: 5,
    confirmOrder: 4,
    totalSale: 'PKR 950,000',
    recovery: 'PKR 710,000',
  },
  {
    id: '5',
    businessName: 'Khan Traders',
    contactPerson: 'Mr. Shakeel Khan',
    segment: 'Trader',
    phone: '0312-3456789',
    city: 'MULTAN',
    brick: 'Cantonment',
    group: 'AGILE',
    product: 'Gambo Fix',
    manager: 'Dr. Ahmed',
    province: 'Punjab',
    date: '2026-05-15',
    status: 'Confirm Order',
    potential: '250 / day',
    visitNotes: 2,
    lineManagerNotes: 3,
    managerNotes: 2,
    confirmOrder: 2,
    totalSale: 'PKR 320,000',
    recovery: 'PKR 240,000',
  },
  {
    id: '6',
    businessName: 'Sunny AIT Center',
    contactPerson: 'Mr. Rashid Iqbal',
    segment: 'AIT',
    phone: '0301-2345678',
    city: 'FAISALABAD',
    brick: 'Jaranwala',
    group: 'QASWA',
    product: 'Colital 1kg',
    manager: 'Dr. Hafiz Muhammad Zakriya',
    province: 'Punjab',
    date: '2026-05-14',
    status: 'Recovery',
    potential: '90,000',
    visitNotes: 4,
    lineManagerNotes: 6,
    managerNotes: 3,
    confirmOrder: 4,
    totalSale: 'PKR 420,000',
    recovery: 'PKR 300,000',
  },
  {
    id: '7',
    businessName: 'Royal Feed Mill',
    contactPerson: 'Mr. Zohaib Butt',
    segment: 'Feed Mill',
    phone: '0322-1234567',
    city: 'LAHORE',
    brick: 'Model Town',
    group: 'FAD',
    product: 'DMG E-SEL 1Ltr',
    manager: 'Dr. Saddam',
    province: 'Punjab',
    date: '2026-05-13',
    status: 'Recovery',
    potential: '15,000 bags',
    visitNotes: 3,
    lineManagerNotes: 4,
    managerNotes: 2,
    confirmOrder: 3,
    totalSale: 'PKR 200,000',
    recovery: 'PKR 120,000',
  },
  {
    id: '8',
    businessName: 'Hyderabad Agri Services',
    contactPerson: 'Dr. M. Waqas',
    segment: 'VA',
    phone: '0300-8765432',
    city: 'HYDERABAD',
    brick: 'LATIFABAD',
    group: 'QASWA',
    product: 'FRA C12 1 Ltr',
    manager: 'Anwer',
    province: 'Sindh',
    date: '2026-05-12',
    status: 'Confirm Order',
    potential: '8-10 / day',
    visitNotes: 2,
    lineManagerNotes: 3,
    managerNotes: 2,
    confirmOrder: 2,
    totalSale: 'PKR 150,000',
    recovery: 'PKR 95,000',
  },
  {
    id: '9',
    businessName: 'Peshawar Poultry',
    contactPerson: 'Mr. Faisal Shah',
    segment: 'Layer',
    phone: '0300-1112223',
    city: 'PESHAWAR',
    brick: 'University Road',
    group: 'AGILE',
    product: 'FRA AC34 10 ltr',
    manager: 'Adil BSM',
    province: 'KPK',
    date: '2026-05-15',
    status: 'Recovery',
    potential: '45,000',
    visitNotes: 3,
    lineManagerNotes: 5,
    managerNotes: 3,
    confirmOrder: 3,
    totalSale: 'PKR 380,000',
    recovery: 'PKR 210,000',
  },
  {
    id: '10',
    businessName: 'Quetta Livestock',
    contactPerson: 'Mr. Ahmed Ali',
    segment: 'Dairy Farm',
    phone: '0300-4445556',
    city: 'QUETTA',
    brick: 'Satellite Town',
    group: 'FAD',
    product: 'FRA AC34 25 ltr',
    manager: 'Dr. Saddam',
    province: 'Balochistan',
    date: '2026-05-11',
    status: 'Confirm Order',
    potential: '150',
    visitNotes: 5,
    lineManagerNotes: 6,
    managerNotes: 4,
    confirmOrder: 4,
    totalSale: 'PKR 750,000',
    recovery: 'PKR 600,000',
  },
  {
    id: '11',
    businessName: 'Burewala Agro',
    contactPerson: 'Mr. Bilal Khan',
    segment: 'Hatchery',
    phone: '0300-7778889',
    city: 'BUREWALA',
    brick: '90 Mor',
    group: 'FAD',
    product: 'NCO Skill 200 1Kg',
    manager: 'Dr. Shakil Ashraf',
    province: 'Punjab',
    date: '2026-05-13',
    status: 'Confirm Order',
    potential: '25,000 bags',
    visitNotes: 4,
    lineManagerNotes: 5,
    managerNotes: 3,
    confirmOrder: 3,
    totalSale: 'PKR 450,000',
    recovery: 'PKR 350,000',
  },
  {
    id: '12',
    businessName: 'D.I Khan Store',
    contactPerson: 'Dr. Hassan Javid',
    segment: 'Feed Mill',
    phone: '0300-9990001',
    city: 'D.I Khan',
    brick: 'Main Area',
    group: 'FAD',
    product: 'Respizan OS 5 Ltr',
    manager: 'Dr. Shakil Ashraf',
    province: 'KPK',
    date: '2026-05-10',
    status: 'Recovery',
    potential: '75,000 bags',
    visitNotes: 7,
    lineManagerNotes: 9,
    managerNotes: 6,
    confirmOrder: 5,
    totalSale: 'PKR 1,200,000',
    recovery: 'PKR 900,000',
  },
  {
    id: '13',
    businessName: 'Elite Vets Sukkur',
    contactPerson: 'Dr. Sarah Ahmad',
    segment: 'Consultant',
    phone: '0300-2223334',
    city: 'Thatta',
    brick: 'Main Town',
    group: 'AGILE',
    product: 'Vitarich D OP',
    manager: 'Dr. Bilal',
    province: 'Sindh',
    date: '2026-05-11',
    status: 'Recovery',
    potential: '10-15 / day',
    visitNotes: 4,
    lineManagerNotes: 4,
    managerNotes: 3,
    confirmOrder: 3,
    totalSale: 'PKR 120,000',
    recovery: 'PKR 100,000',
  },
  {
    id: '14',
    businessName: 'April Feed Mill',
    contactPerson: 'Mr. April Person',
    segment: 'Farmer',
    phone: '0300-5555555',
    city: 'LAHORE',
    brick: 'Model Town',
    group: 'AGILE',
    product: 'FRA AC34 1 ltr',
    manager: 'Adil BSM',
    province: 'Punjab',
    date: '2026-04-15',
    status: 'Recovery',
    potential: '50,000',
    visitNotes: 5,
    lineManagerNotes: 7,
    managerNotes: 4,
    confirmOrder: 5,
    totalSale: 'PKR 350,000',
    recovery: 'PKR 220,000',
  },
  {
    id: '15',
    businessName: 'April Poultry Farm',
    contactPerson: 'Mr. April Owner',
    segment: 'Broiler',
    phone: '0300-6666666',
    city: 'Karachi',
    brick: 'SADDAR',
    group: 'AGILE',
    product: 'Gambo Fix',
    manager: 'Adil BSM',
    province: 'Sindh',
    date: '2026-04-20',
    status: 'Confirm Order',
    potential: '30,000',
    visitNotes: 3,
    lineManagerNotes: 5,
    managerNotes: 2,
    confirmOrder: 4,
    totalSale: 'PKR 550,000',
    recovery: 'PKR 400,000',
  },
];

export const timeline: TimelineEntry[] = [
  {
    id: '1',
    role: 'Sales Person',
    name: 'Adi BSM',
    time: '10:15 AM',
    date: 'Monday, May 12, 2026',
    message: 'Visited M. Islam Medical Store. Introduced Tylovalo Forte (Aceclofenac + Paracetamol). Customer showed interest in first order. Provided brochure and price list.',
    promotedProduct: 'Tylovalo Forte',
    status: 'Recovery',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Adi',
  },
  {
    id: '3',
    role: 'Sales Person',
    name: 'Adi BSM',
    time: '11:10 AM',
    date: 'Monday, May 12, 2026',
    message: 'Order confirmed by customer. Delivery scheduled for 13-05-2026 (Morning). Customer assured full payment on delivery.',
    promotedProduct: 'Tylovalo Forte',
    status: 'Confirm Order',
    metrics: {
      qty: '500 Units',
      totalSale: 'PKR 80,000',
      recovery: 'PKR 72,000',
    },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Adi',
  },
  {
    id: '4',
    role: 'Line Manager',
    name: 'Asif Mehmood',
    time: '11:35 AM',
    date: 'Monday, May 12, 2026',
    message: 'Great progress! Ensure timely delivery and proper stock availability. Follow up tomorrow post delivery for payment confirmation.',
    status: 'Customer Meeting',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Asif',
  },
  {
    id: '5',
    role: 'Manager',
    name: 'M. Imran Khalid',
    time: '12:10 PM',
    date: 'Monday, May 12, 2026',
    message: 'Well done Adi. Since customer is recovering the outstanding amount, please ensure collection by promised date and update in system.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Imran',
  },
  {
    id: '6',
    role: 'Sales Person',
    name: 'Adi BSM',
    time: '04:20 PM',
    date: 'Monday, May 12, 2026',
    message: 'Customer agreed to recover outstanding amount of PKR 72,000 by 15-05-2026. Recovery commitment confirmed.',
    status: 'Recovery',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Adi',
  },
];
